package org.risa.android.data;

import java.util.ArrayList;
import java.util.Collection;
import java.util.Collections;
import java.util.Comparator;
import java.util.List;

import android.widget.ImageView;

/**
 * Base class that classifies an identifiable target.  For the sake 
 * of our scope targets are general tow dimensional images that 
 * can be identified using mood stocks api.
 * 
 * @author Michael Hotan, michael.hotan@gmail.com
 */
public abstract class Target {

	/**
	 * Global Unique ID.
	 * Note: That UIDs are set by the server.
	 */
	private final String mUID;
	
	/**
	 * This String Represents a readable string 
	 */
	private final String mReadableString;
	
	/**
	 * Collection of items that can be interacted with within the target.
	 * <b>This requires some kind of inherent order to the items.
	 */
	private final List<Item> mItems;
	
	/**
	 * 
	 */
	private Comparator<Item> mOrderComparator;
	
	/**
	 * Creates a target with the associated Global unique id.
	 * 
	 * @param uid Global Universal ID
	 */
	public Target(String uid) {
		this("", uid);
	}
	
	/**
	 * When creating a targer we have to associate the target with a 
	 * global identifier "uid" that we set.  We alse have the ability to 
	 * have our clients set a human readable identifier to their advertisements
	 * as well.
	 * 
	 * @param identifier A human readable identifier created by clients
	 * @param uid Unique ID generated by us
	 */
	public Target(String identifier, String uid) {
		if (identifier == null) 
			throw new NullPointerException(Target.class.getSimpleName() + "() Illegal null identifier");
		if (uid == null) 
			throw new NullPointerException(Target.class.getSimpleName() + "() Illegal null global identification number");
		
		mUID = uid;
		mReadableString = identifier;
		mItems = new ArrayList<Item>();
	}
	
	/**
	 * Returns the readable string that is associates with this target.
	 * 
	 * @return String identification with this target.
	 */
	public String getReadableIdentifier() {
		return mReadableString;
	}
	
	/**
	 * Get all the interactable components within this Target.
	 * 
	 * @return All the interactable objects within the target
	 */
	public List<Item> getItems() {
		return getItems(null);
	}
	
	/**
	 * Get all the interactable components within this Target.
	 * 
	 * @param orderComparator Comparator that mandates the order of the items.
	 * @return All the interactable objects within the target
	 */
	public List<Item> getItems(Comparator<Item> orderComparator) {
		List<Item> items = new ArrayList<Item>(mItems);
		if (orderComparator == null)
			return items;
		Collections.sort(items, orderComparator);
		return items;
	}
	
	/**
	 * Adds a interactable item or overwrites any equal item within this
	 * Target.
	 * 
	 * @param item item to add that is interactable.
	 */
	public void addItem(Item item) {
		if (item == null) return;
		if (mItems.contains(item)) return;
		mItems.add(item);
	}
	
	/**
	 * Removes an interactable item if it exists within this target.
	 * 
	 * @param item Item to remove
	 */
	public void removeItem(Item item) {
		mItems.remove(item);
	}
	
	/**
	 * Remove all the interactable components and returns them
	 * 
	 * @return Returns all the Interactable components of this.
	 */
	public Collection<Item> clearInteractables() {
		Collection<Item> interactables = getItems();
		mItems.clear();
		return interactables;
	}
	
	/**
	 * Returns the Global Unique ID for this target.
	 * 
	 * @return The Global Unique ID
	 */
	public String getUID() {
		return mUID;
	}
	
	/**
	 * Passes the responsibility to all subclasses to load an image within this view.
	 * This must be a synchronous operation. Therefore classes must pre load all images before 
	 * setting the views image.
	 * 
	 * @param view View to load  
	 */
	public abstract void loadImage(ImageView view);

	/**
	 * Every image has a bounding area.  This function returns the boundings area
	 * 
	 * @return The original bounding area of this target
	 */
	public abstract RectangularDimension getDimensions();
		
}
