package org.risa.android.data;

import java.util.Collection;
import java.util.HashSet;
import java.util.Set;

import android.widget.ImageView;

/**
 * Base class that classifies an identifiable target.  For the sake 
 * of our scope targets are general tow dimensional images that 
 * can be identified using mood stocks api.
 * 
 * @author Michael Hotan, michael.hotan@gmail.com
 */
public abstract class Target {

	/**
	 * Global Unique ID.
	 * Note: That UIDs are set by the server.
	 */
	private final String mUID;
	
	/**
	 * This String Represents a readable string 
	 */
	private final String mReadableString;
	
	/**
	 * Collection of items that can be interacted with within the target.
	 */
	private final Set<Interactable> mInteractables;
	
	/**
	 * Creates a target with the associated Global unique id.
	 * 
	 * @param uid Global Universal ID
	 */
	public Target(String uid) {
		this("", uid);
	}
	
	/**
	 * When creating a targer we have to associate the target with a 
	 * global identifier "uid" that we set.  We alse have the ability to 
	 * have our clients set a human readable identifier to their advertisements
	 * as well.
	 * 
	 * @param identifier A human readable identifier created by clients
	 * @param uid Unique ID generated by us
	 */
	public Target(String identifier, String uid) {
		if (identifier == null) 
			throw new NullPointerException(Target.class.getSimpleName() + "() Illegal null identifier");
		if (uid == null) 
			throw new NullPointerException(Target.class.getSimpleName() + "() Illegal null global identification number");
		
		mUID = uid;
		mReadableString = identifier;
		mInteractables = new HashSet<Interactable>();
	}
	
	/**
	 * 
	 * 
	 * @return
	 */
	public String getReadableIdentifier() {
		return mReadableString;
	}
	
	/**
	 * Get all the interactable components within this Target.
	 * 
	 * @return All the interactable objects within the target
	 */
	public Collection<Interactable> getInteractables() {
		return new HashSet<Interactable>(mInteractables);
	}
	
	/**
	 * Adds a interactable item or overwrites any equal item within this
	 * Target.
	 * 
	 * @param item item to add that is interactable.
	 */
	public void addInteractable(Interactable item) {
		mInteractables.add(item);
	}
	
	/**
	 * Removes an interactable item if it exists within this target.
	 * 
	 * @param item Item to remove
	 */
	public void removeInteractable(Interactable item) {
		mInteractables.remove(item);
	}
	
	/**
	 * Remove all the interactable components and returns them
	 * 
	 * @return Returns all the Interactable components of this.
	 */
	public Collection<Interactable> clearInteractables() {
		Collection<Interactable> interactables = getInteractables();
		mInteractables.clear();
		return interactables;
	}
	
	/**
	 * Returns the Global Unique ID for this target.
	 * 
	 * @return The Global Unique ID
	 */
	public String getUID() {
		return mUID;
	}
	
	/**
	 * Passes the responsibility to all subclasses to load an image within this view.
	 * This must be a synchronous operation. Therefore classes must pre load all images before 
	 * setting the views image.
	 * 
	 * @param view View to load  
	 */
	public abstract void loadImage(ImageView view);

	/**
	 * Every image has a bounding area.  This function returns the boundings area
	 * 
	 * @return The original bounding area of this target
	 */
	public abstract RectangularDimension getDimensions();
		
}
